### ISSUE TITLE
It doesn't like Java SE 16 very much?

### ISSUE THREAD

**Issue by nobeltnium** [quantumcored/remote_hacker_probe#10]
when i run the run-on-linux.desktop, it won't do anything. 
So i ran `java -jar RHP.jar` in the terminal, it gives me error:
```
Error: LinkageError occurred while loading main class rhp.MainWindow
        java.lang.UnsupportedClassVersionError: rhp/MainWindow has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```
I installed the latest version of Java SE 16, i know the reccommendation is Java 15 but downloading it require register and that's a hassle

**Comment by quantumcore** [comment]
I fixed the Java Version error. Grab the latest release if you haven't already and try it. If it doesn't work then let me know here.

**Comment by nobeltnium** [comment]
Hi quantumcore, the version i'm using is the latest release (Remote Hacker Probe V.2.1). And this is the version that i'm having trouble with. I'm not using any release other than 2.1
Regards.

**Comment by quantumcore** [comment]
Do _java -version_ and double check the version.

**Comment by nobeltnium** [comment]
Hi quantumcore, i checked the java version as you suggested, turn out i was running on java 11 (it came preinstalled on my system). So i removed it, and reinstall java 16. Now it's working like it should.
Many thanks for your help.

**Comment by kgnfth** [comment]
i have the same problem

```
$ java -version
> java version "1.8.0_301"
> Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
> Java HotSpot(TM) Client VM (build 25.301-b09, mixed mode)
```
