### ISSUE TITLE
client won't reconnect after server restart

### ISSUE THREAD

**Issue by nobeltnium** [quantumcored/remote_hacker_probe#11]
When i stop the server and run it again (i'm talking about stop/killing the application and run it again. Not rebooting the machine). Clients won't connect back to the server unless i execute the evil file once more.
Is this a bug or a feature :sweat_smile:

**Comment by quantumcore** [comment]
Did you try waiting? Give some time to the client. Maybe if you do this when some background process is pending, like if you do reflective dll injection and the server disconnects. It may take some time for the client to clear up used memory and realize it's disconnected.

(For a simple experiment you can check that when the bug happens, The client is taking alot of memory. You can check this in task manager)

Anyway, Give it a moment. I think this might be a bug. So for a temporal fix if used in real world scenarios, Install persistence as backup just in case.

I'll look into it. 

Thanks for reporting!  😅

**Comment by nobeltnium** [comment]
hi quantumcore, i did some test like you suggest waiting for about 2 hours. But the connection wont establish back.
This is a screenshot of the memory usage when it was disconnected.
![image](https://user-images.githubusercontent.com/70144761/133915354-671c62db-0a3e-41db-8f9d-db0d69cea33e.png)
FYI Both machine are within LAN and no any kind of AV is running on the windows machine

**Comment by quantumcore** [comment]
What was the cause of the disconnection?

**Comment by nobeltnium** [comment]
well, closing the server and open it back on and the client won't reconnect, as i mentioned above. 
Sorry for the late reply, i was so busy lately

**Comment by quantumcore** [comment]
Strange, I just tested it and it works for me. I'll try to reproduce the problem and fix it.

**Comment by nobeltnium** [comment]
To recreate the situation, first i execute the evil file on a windows machine while the server is listening. Once the file is executed, connection is established
![image](https://user-images.githubusercontent.com/70144761/134537841-7f21d6dc-86a2-4c27-af60-829e381a0146.png)

then close the server, and run it again
![image](https://user-images.githubusercontent.com/70144761/134537992-a7e968d8-8a54-4e93-95eb-89b5f4cf11ff.png)

Once the server is back, the connection cannot be establish. Even after a long period of time (up to 2 hours).

The evil file is still running on windows machine
![image](https://user-images.githubusercontent.com/70144761/134538561-e5037cd5-2cbd-45be-a647-9aead44a0108.png)

To be able to reconnect to the server, the evil file need to be executed again. Result in 2 instances of it running
![image](https://user-images.githubusercontent.com/70144761/134538809-3f9cc5d6-4b41-446f-8ff5-027626ea7de3.png)

**Comment by quantumcore** [comment]
What is the payload you're using?

**Comment by nobeltnium** [comment]
I'm using the standard payload builder that comes with Remote Hacker Probe. With server host and server port information. Without any other options (no Infect USB Drives, no DLL Loader).
![image](https://user-images.githubusercontent.com/70144761/134540551-fa827f84-3d88-45b8-946d-5f09e982fa9b.png)

**Comment by quantumcore** [comment]
Hey! Can you try testing if this error still exists with the latest release?

**Comment by Elmani335** [comment]
> Hey! Can you try testing if this error still exists with the latest release?

Hey ! I have this issue too, I'll try the new version and tell if it does work soon ! thx

**Comment by quantumcore** [comment]
@Elmani335 Yes please do so asap.

**Comment by Elmani335** [comment]
> 

Hey I tried on my vm the new version is working, but i have few questions :

![image](https://user-images.githubusercontent.com/52176963/152394834-b2c03206-df48-4a04-909c-2ae11b612c83.png)
 on this image ^ how to use the reflective loader handler ? i dont' have any machines apperaing here and I don't know how to use it

![image](https://user-images.githubusercontent.com/52176963/152395060-e36a5d77-b391-4b52-b5f2-d7f8ee20fa24.png)
and on this images ^ on the persistance panel, what does the key mean ? what does it actually do ? 

Thx !

**Comment by Elmani335** [comment]
> 

@quantumcore

**Comment by quantumcore** [comment]
@Elmani335 Yo that's off the issue, hit me up on [discord](https://discordapp.com/invite/8snh7nx), I'll explain you over there.

also will add a wiki for detailed explanations, later. 
Meanwhile, Read about the Reflective Loader here ; https://quantumcored.com/index.php/2021/03/11/running-completely-in-memory-using-remote-hacker-probes-new-dll-loader-payload/
