### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by NovaFlux562** [quantumcored/remote_hacker_probe#15]
Hi I know you might be busy 
This is just a suggestion
can you add support for
IRC,HTTP so it doesn't just rely on port forwading Like Saefko Attack systems
where I live port forwading is pain in the ass
expecting a reply 
Thanks.

**Comment by quantumcore** [comment]
Great idea! Thanks! I'll be implementing new things soon!

IRC HTTP is too common, We need another method.

**Comment by quantumcore** [comment]
If you have any ideas, do tell please. :)

**Comment by NovaFlux562** [comment]
Mate you're the expert :3 port forwarding in
pak sucks and using vpn to port forward  isn't reliable and using rat on rdp
doesn't give the smoothness

**Comment by quantumcore** [comment]
@Dex0xm I'm from Pak too. Port forwarding anywhere actually doesn't have to do with where you're from. IT usually works fine. In most cases the internet is shit that leads to slow connections with high ping. 

And yes, as we know, We do have shitty internet. Try using services like portmap.io. Anyway, I'll think of something regarding this. I have been thinking about similar problem.

**Comment by quantumcore** [comment]
get on [discord](https://discordapp.com/invite/8snh7nx)
