### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by mrsoms** [quantumcored/remote_hacker_probe#16]
After building a client with 0.0.0.0:1234  and running, i dont receive any connection

**Comment by quantumcore** [comment]
That would work only if its run on the same machine as the server. 

To make it run on entire LAN, Use local ip of your computer which is running the server. 

To make it run on Wan, do port forwarding. For more information, google it.

**Comment by lele1302** [comment]
What should I type in the probe, to astablish a connection?
My Ip adress?
should I change my server, from 0.0.0.0?
