### ISSUE TITLE
Serious issue with remote hacker probe

### ISSUE THREAD

**Issue by augustgl** [quantumcored/remote_hacker_probe#2]
It's too swag

**Comment by graysuit** [comment]
@augustgl 
You think we are magicians ? If you think then thanks alot. lol
How we know what issue you faced ?

**Comment by augustgl** [comment]
> @augustgl 
> 
> You think we are magicians ? If you think then thanks alot. lol
> 
> How we know what issue you faced ?

I already said what the issue was. It was too swag

**Comment by swagkarna** [comment]
> @augustgl
> You think we are magicians ? If you think then thanks alot. lol
> How we know what issue you faced ?

I'm here Lol

**Comment by graysuit** [comment]
@swagkarna lol,
I didn't understood what meaning of **swag** ?
`its too swag`
swag is working style in hindi but not sure what its doing in english.
https://translate.google.com/?sl=en&tl=ur&text=swag&op=translate

**Comment by graysuit** [comment]
@augustgl  You mean that form is alot heavy on ram and memory ?

**Comment by quantumcore** [comment]
@augustgl I have this problem too! I can't figure out how to fix it! :sob: :joy:

**Comment by graysuit** [comment]
> 
> 
> @augustgl You mean that form is alot heavy on ram and memory ?

@quantumcore Is this problem ?
I guess these options specify how much RAM should form take:
`_JAVA_OPTIONS: -Xmx800M`
