### ISSUE TITLE
Some questions.

### ISSUE THREAD

**Issue by n0vacorp** [quantumcored/remote_hacker_probe#20]
Hello, I’m Alpha. I’m new to pen testing, and came across this repo. I have a question, what do you use to configure the client? Do I use my public or private IP address? What port do I put it as? Also, does the client only work on computers connected to the same network as I? Please give a step-by-step explanation as I am very new to pen testing and don’t know much.Thank you!

**Comment by quantumcore** [comment]
Hello Alpha. To understand how this works, Learn about networking basics, Specifically, Server and client. 

> does the client only work on computers connected to the same network as I?

That is not nessecary. 

> Please give a step-by-step explanation as I am very new to pen testing and don’t know much.
I'd love to do that. But I don't have the time and energy to explain step by step to you. All of this knowledge is out there for free.
Good luck on your journey ahead! :)
