### ISSUE TITLE
Doesn't seem to open

### ISSUE THREAD

**Issue by ghost** [quantumcored/remote_hacker_probe#3]
Hey, I've stuck this on a fresh virtual machine. I downloaded and installed Java and the RHP icon has changed to the java logo as expected, but when I either open the "run on Windows" bat file, or directly open the RHP file in Java, nothing happens. 

Well, to be more specific, run on windows bat brings up cmd for a fraction of a second and the nothing, and RHP shows a loading icon on the mouse, also for a fraction of a second, but that's it. I've tried twice, with seperate virtual machines, with antivirus off on both my host machine and the guest machine (downloaded to host and moved to guest).

Am I being stupid here?

Thanks

**Comment by quantumcore** [comment]
I think the java version you installed is not compatible. 

Lets see what the error is, Can you open cmd and navigate to the RHP directory. 
Then type _java -jar RHP.jar_ and paste the output here?

**Comment by ghost** [comment]
Thanks for your reply, yep, what you said was the issue. I was a bit confused by Java 11 downloads (could originally only find a zip of files and not an exe) so just downloaded the latest Java 8, where the error below is from. I did some more digging and tried a Java 11 exe download from outside of the Java/Oracle website and it then worked fine, thanks! Unfortunately the features set isn't quite what I'm looking for at the moment, but glad to know this works and I'll keep my eyes on any future updates! :D

> Exception in thread "main" java.lang.UnsupportedClassVersionError: rhp/MainWindow has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
>         at java.lang.ClassLoader.defineClass1(Native Method)
>         at java.lang.ClassLoader.defineClass(Unknown Source)
>         at java.security.SecureClassLoader.defineClass(Unknown Source)
>         at java.net.URLClassLoader.defineClass(Unknown Source)
>         at java.net.URLClassLoader.access$100(Unknown Source)
>         at java.net.URLClassLoader$1.run(Unknown Source)
>         at java.net.URLClassLoader$1.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.net.URLClassLoader.findClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at java.lang.Class.forName0(Native Method)
>         at java.lang.Class.forName(Unknown Source)
>         at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:59)

**Comment by quantumcore** [comment]
Don't give up just yet, Install this and try again. I guarantee you it will be worth it.
https://www.oracle.com/java/technologies/javase-jdk15-downloads.html

**Comment by graysuit** [comment]
In my case, I was using `java.exe` of `jdk`. Instead I should use`java.exe` of `jre`. 
I thought that its version problem. But actually its java runtime problem.
Now it works fine.
