### ISSUE TITLE
Ngrok and local

### ISSUE THREAD

**Issue by nikolay06** [quantumcored/remote_hacker_probe#4]
Thank you for your work! Great project ! I have a question sir. When connecting ngrok form build , what to do with the local network settings ? I can't connect ngrok as well as locally. Thank you.

**Comment by quantumcore** [comment]
@nikolay06 Thank you, Glad you like my work. 

I can give you a demonstration, I'm going to assume you're using a Linux based Operating System. My Demo is using Kali 2021 Virtual box Image. You can get it from here. 
https://www.offensive-security.com/kali-linux-vm-vmware-virtualbox-image-download/

**But the same steps will work on Any operating System.** 

So run an ngrok tcp tunnel on Port ``1234``, Default RHP Port, IT should look like this.
![1](https://i.imgur.com/7CpOjCX.png)

That tcp://**ngrok host name**:_Port_. That is where the Probe should be connecting.
At the moment, RHP does not support hostnames, So we're gonna use ipv4 for that.
To get IP of that hostname, simply ping it. 
![2](https://i.imgur.com/24ne9MP.png)

That IP and the _Port_ with the Hostname are the Server Host and Server Port you use to build the Probe. Connection works.

Let me know if you have any other problems. **Consider [Upgrading](https://quantumcored.com/index.php/the-remote-hacker-probe/) for access to more features or supporting me! Thank you for using Remote Hacker Probe!**
