### ISSUE TITLE
Bind Error

### ISSUE THREAD

**Issue by Sucukali** [quantumcored/remote_hacker_probe#5]
Whenever I start the program it says Bind Error : java.net.BindException: adress already in use: bind.
I can't seem to fix this issue.
![dddd](https://user-images.githubusercontent.com/77283794/111880210-547f3300-89aa-11eb-8000-cef91be3c791.PNG)

**Comment by quantumcore** [comment]
Bind error means that there is something else listening on 0.0.0.0:1234 or the host and port of RHP Server.
Make sure you open RHP once. There should only be one instance of RHP.
