### ISSUE TITLE
problem open source code 

### ISSUE THREAD

**Issue by chinemys** [quantumcored/remote_hacker_probe#6]
hi,what did you use to do the source code project? i imported with eclips and i get more than 100 errors

**Comment by quantumcore** [comment]
You probably imported the entire project in eclipse.
Import the folder ``gui`` in eclipse only, https://github.com/quantumcored/remote_hacker_probe/tree/main/gui

**Comment by chinemys** [comment]
thanks but Another problems

Description	Resource	Path	Location	Type
ArtifactDescriptorException: Failed to read artifact descriptor for commons-io:commons-io:jar:2.6: ArtifactResolutionException: Failure to transfer commons-io:commons-io:pom:2.6 from http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact commons-io:commons-io:pom:2.6 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer http://repo.maven.apache.org/maven2/commons-io/commons-io/2.6/commons-io-2.6.pom. Error code 501, HTTPS Required	pom.xml	/rhp	line 1	Maven Dependency Problem
ArtifactDescriptorException: Failed to read artifact descriptor for org.jxmapviewer:jxmapviewer2:jar:2.5: ArtifactResolutionException: Failure to transfer org.jxmapviewer:jxmapviewer2:pom:2.5 from http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact org.jxmapviewer:jxmapviewer2:pom:2.5 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer http://repo.maven.apache.org/maven2/org/jxmapviewer/jxmapviewer2/2.5/jxmapviewer2-2.5.pom. Error code 501, HTTPS Required	pom.xml	/rhp	line 1	Maven Dependency Problem
Project 'rhp' is missing required source folder: 'src/main/resources'	rhp		Build path	Build Path Problem
ArtifactDescriptorException: Failed to read artifact descriptor for com.googlecode.json-simple:json-simple:jar:1.1.1: ArtifactResolutionException: Failure to transfer com.googlecode.json-simple:json-simple:pom:1.1.1 from http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact com.googlecode.json-simple:json-simple:pom:1.1.1 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer http://repo.maven.apache.org/maven2/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.pom. Error code 501, HTTPS Required	pom.xml	/rhp	line 1	Maven Dependency Problem
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-compiler-plugin:2.3.2:testCompile (execution: default-testCompile, phase: test-compile)	pom.xml	/rhp	line 1	Maven Project Build Lifecycle Mapping Problem
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (execution: default-compile, phase: compile)	pom.xml	/rhp	line 1	Maven Project Build Lifecycle Mapping Problem
ArtifactDescriptorException: Failed to read artifact descriptor for com.github.weisj:darklaf-core:jar:2.5.3: ArtifactResolutionException: Failure to transfer com.github.weisj:darklaf-core:pom:2.5.3 from http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact com.github.weisj:darklaf-core:pom:2.5.3 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer http://repo.maven.apache.org/maven2/com/github/weisj/darklaf-core/2.5.3/darklaf-core-2.5.3.pom. Error code 501, HTTPS Required	pom.xml	/rhp	line 1	Maven Dependency Problem
ArtifactDescriptorException: Failed to read artifact descriptor for com.maxmind.geoip2:geoip2:jar:2.15.0: ArtifactResolutionException: Failure to transfer com.maxmind.geoip2:geoip2:pom:2.15.0 from http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact com.maxmind.geoip2:geoip2:pom:2.15.0 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer http://repo.maven.apache.org/maven2/com/maxmind/geoip2/geoip2/2.15.0/geoip2-2.15.0.pom. Error code 501, HTTPS Required	pom.xml	/rhp	line 1	Maven Dependency Problem
CoreException: Could not calculate build plan: Plugin org.apache.maven.plugins:maven-compiler-plugin:2.3.2 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-compiler-plugin:jar:2.3.2: ArtifactResolutionException: Failure to transfer org.apache.maven.plugins:maven-compiler-plugin:pom:2.3.2 from http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact org.apache.maven.plugins:maven-compiler-plugin:pom:2.3.2 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/2.3.2/maven-compiler-plugin-2.3.2.pom. Error code 501, HTTPS Required	pom.xml	/rhp	line 1	Maven Project Build Lifecycle Mapping Problem
The project cannot be built until build path errors are resolved	rhp		Unknown	Java Problem
Project 'rhp' is missing required source folder: 'src/test/resources'	rhp		Build path	Build Path Problem

**Comment by chinemys** [comment]
Description	Resource	Path	Location	Type
ArtifactDescriptorException: Failed to read artifact descriptor for commons-io:commons-io:jar:2.6: ArtifactResolutionException: Failure to transfer commons-io:commons-io:pom:2.6 from http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact commons-io:commons-io:pom:2.6 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer http://repo.maven.apache.org/maven2/commons-io/commons-io/2.6/commons-io-2.6.pom. Error code 501, HTTPS Required	pom.xml	/rhp	line 1	Maven Dependency Problem
ArtifactDescriptorException: Failed to read artifact descriptor for org.jxmapviewer:jxmapviewer2:jar:2.5: ArtifactResolutionException: Failure to transfer org.jxmapviewer:jxmapviewer2:pom:2.5 from http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact org.jxmapviewer:jxmapviewer2:pom:2.5 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer http://repo.maven.apache.org/maven2/org/jxmapviewer/jxmapviewer2/2.5/jxmapviewer2-2.5.pom. Error code 501, HTTPS Required	pom.xml	/rhp	line 1	Maven Dependency Problem
Project 'rhp' is missing required source folder: 'src/main/resources'	rhp		Build path	Build Path Problem
ArtifactDescriptorException: Failed to read artifact descriptor for com.googlecode.json-simple:json-simple:jar:1.1.1: ArtifactResolutionException: Failure to transfer com.googlecode.json-simple:json-simple:pom:1.1.1 from http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact com.googlecode.json-simple:json-simple:pom:1.1.1 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer http://repo.maven.apache.org/maven2/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.pom. Error code 501, HTTPS Required	pom.xml	/rhp	line 1	Maven Dependency Problem
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-compiler-plugin:2.3.2:testCompile (execution: default-testCompile, phase: test-compile)	pom.xml	/rhp	line 1	Maven Project Build Lifecycle Mapping Problem
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (execution: default-compile, phase: compile)	pom.xml	/rhp	line 1	Maven Project Build Lifecycle Mapping Problem
ArtifactDescriptorException: Failed to read artifact descriptor for com.github.weisj:darklaf-core:jar:2.5.3: ArtifactResolutionException: Failure to transfer com.github.weisj:darklaf-core:pom:2.5.3 from http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact com.github.weisj:darklaf-core:pom:2.5.3 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer http://repo.maven.apache.org/maven2/com/github/weisj/darklaf-core/2.5.3/darklaf-core-2.5.3.pom. Error code 501, HTTPS Required	pom.xml	/rhp	line 1	Maven Dependency Problem
ArtifactDescriptorException: Failed to read artifact descriptor for com.maxmind.geoip2:geoip2:jar:2.15.0: ArtifactResolutionException: Failure to transfer com.maxmind.geoip2:geoip2:pom:2.15.0 from http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact com.maxmind.geoip2:geoip2:pom:2.15.0 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer http://repo.maven.apache.org/maven2/com/maxmind/geoip2/geoip2/2.15.0/geoip2-2.15.0.pom. Error code 501, HTTPS Required	pom.xml	/rhp	line 1	Maven Dependency Problem
CoreException: Could not calculate build plan: Plugin org.apache.maven.plugins:maven-compiler-plugin:2.3.2 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-compiler-plugin:jar:2.3.2: ArtifactResolutionException: Failure to transfer org.apache.maven.plugins:maven-compiler-plugin:pom:2.3.2 from http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact org.apache.maven.plugins:maven-compiler-plugin:pom:2.3.2 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/2.3.2/maven-compiler-plugin-2.3.2.pom. Error code 501, HTTPS Required	pom.xml	/rhp	line 1	Maven Project Build Lifecycle Mapping Problem
The project cannot be built until build path errors are resolved	rhp		Unknown	Java Problem
Project 'rhp' is missing required source folder: 'src/test/resources'	rhp		Build path	Build Path Problem

**Comment by chinemys** [comment]
thanks,but there seems to be something missing:

Description	Resource	Path	Location	Type
Project 'rhp' is missing required source folder: 'src/main/resources'	rhp		Build path	Build Path Problem
Project 'rhp' is missing required source folder: 'src/test/resources'	rhp		Build path	Build Path Problem
The project cannot be built until build path errors are resolved	rhp		Unknown	Java Problem

**Comment by quantumcore** [comment]
I am unsure of what the problem is here, But can you try 
1. Creating empty directory ``src/main/resources`` and ``src/test/resources``. 
2. Regarding Maven errors, Create Eclipse Maven project and add Pom XML located here.
https://github.com/quantumcored/remote_hacker_probe/blob/main/gui/pom.xml
3. IF all that doesn't work, Try creating a Empty Maven project, Add The pom xml thats linked above, And add all the files that are here : https://github.com/quantumcored/remote_hacker_probe/tree/main/gui/src/main/java/rhp one by one. And check if it works then.

**Comment by chinemys** [comment]
thanks, I had already solved "Maven errors".
i have already tried to create empty folders, but when i import again, i get 157 warnings and i can't build anything anyway.
I am using Eclipse Ide version 2021-03 (4.19.0)

Description	Resource	Path	Location	Type
DefaultListModel is a raw type. References to generic type DefaultListModel<E> should be parameterized	FileManager.java	/rhp/src/main/java/rhp	line 267	Java Problem
DefaultListModel is a raw type. References to generic type DefaultListModel<E> should be parameterized	FileManager.java	/rhp/src/main/java/rhp	line 324	Java Problem
DefaultListModel is a raw type. References to generic type DefaultListModel<E> should be parameterized	NetworkScanner.java	/rhp/src/main/java/rhp	line 43	Java Problem
DefaultListModel is a raw type. References to generic type DefaultListModel<E> should be parameterized	NetworkScanner.java	/rhp/src/main/java/rhp	line 43	Java Problem
DefaultListModel is a raw type. References to generic type DefaultListModel<E> should be parameterized	NetworkScanner.java	/rhp/src/main/java/rhp	line 45	Java Problem
DefaultListModel is a raw type. References to generic type DefaultListModel<E> should be parameterized	NetworkScanner.java	/rhp/src/main/java/rhp	line 45	Java Problem
DefaultListModel is a raw type. References to generic type DefaultListModel<E> should be parameterized	NetworkScanner.java	/rhp/src/main/java/rhp	line 46	Java Problem
DefaultListModel is a raw type. References to generic type DefaultListModel<E> should be parameterized	NetworkScanner.java	/rhp/src/main/java/rhp	line 46	Java Problem
DefaultListModel is a raw type. References to generic type DefaultListModel<E> should be parameterized	NetworkScanner.java	/rhp/src/main/java/rhp	line 47	Java Problem
DefaultListModel is a raw type. References to generic type DefaultListModel<E> should be parameterized	NetworkScanner.java	/rhp/src/main/java/rhp	line 47	Java Problem
JComboBox is a raw type. References to generic type JComboBox<E> should be parameterized	FileManager.java	/rhp/src/main/java/rhp	line 476	Java Problem
JComboBox is a raw type. References to generic type JComboBox<E> should be parameterized	FileManager.java	/rhp/src/main/java/rhp	line 476	Java Problem
JComboBox is a raw type. References to generic type JComboBox<E> should be parameterized	MsgBox.java	/rhp/src/main/java/rhp	line 68	Java Problem
JComboBox is a raw type. References to generic type JComboBox<E> should be parameterized	MsgBox.java	/rhp/src/main/java/rhp	line 68	Java Problem
JComboBox is a raw type. References to generic type JComboBox<E> should be parameterized	NetworkScanner.java	/rhp/src/main/java/rhp	line 410	Java Problem
JComboBox is a raw type. References to generic type JComboBox<E> should be parameterized	NetworkScanner.java	/rhp/src/main/java/rhp	line 410	Java Problem
JComboBox is a raw type. References to generic type JComboBox<E> should be parameterized	Settings.java	/rhp/src/main/java/rhp	line 138	Java Problem
JComboBox is a raw type. References to generic type JComboBox<E> should be parameterized	Settings.java	/rhp/src/main/java/rhp	line 138	Java Problem
JList is a raw type. References to generic type JList<E> should be parameterized	FileManager.java	/rhp/src/main/java/rhp	line 263	Java Problem
JList is a raw type. References to generic type JList<E> should be parameterized	FileManager.java	/rhp/src/main/java/rhp	line 325	Java Problem
JList is a raw type. References to generic type JList<E> should be parameterized	FileManager.java	/rhp/src/main/java/rhp	line 435	Java Problem
JList is a raw type. References to generic type JList<E> should be parameterized	NetworkScanner.java	/rhp/src/main/java/rhp	line 42	Java Problem
JList is a raw type. References to generic type JList<E> should be parameterized	NetworkScanner.java	/rhp/src/main/java/rhp	line 44	Java Problem
JList is a raw type. References to generic type JList<E> should be parameterized	NetworkScanner.java	/rhp/src/main/java/rhp	line 51	Java Problem
JList is a raw type. References to generic type JList<E> should be parameterized	NetworkScanner.java	/rhp/src/main/java/rhp	line 54	Java Problem
JList is a raw type. References to generic type JList<E> should be parameterized	NetworkScanner.java	/rhp/src/main/java/rhp	line 313	Java Problem
JList is a raw type. References to generic type JList<E> should be parameterized	NetworkScanner.java	/rhp/src/main/java/rhp	line 336	Java Problem
JList is a raw type. References to generic type JList<E> should be parameterized	NetworkScanner.java	/rhp/src/main/java/rhp	line 497	Java Problem
JList is a raw type. References to generic type JList<E> should be parameterized	NetworkScanner.java	/rhp/src/main/java/rhp	line 644	Java Problem
The assignment to variable value has no effect	Map.java	/rhp/src/main/java/rhp	line 43	Java Problem
The import com.maxmind.geoip2.record.City is never used	Server.java	/rhp/src/main/java/rhp	line 13	Java Problem
The import com.maxmind.geoip2.record.Country is never used	Server.java	/rhp/src/main/java/rhp	line 14	Java Problem
The import com.maxmind.geoip2.record.Locat

**Comment by quantumcore** [comment]
A simple search on the Error and I found this.
> JList is a raw type as of Java 1.7, the same goes for a couple more of swing components.

Check your Java version. You need to have Java 15. 
https://www.oracle.com/java/technologies/javase-jdk15-downloads.html

**Comment by chinemys** [comment]
i reinstalled java to jdk version 15.0.2. I .
libraries are right.
but the java problem persists.

then I wanted to ask you something else.
I am trying the build you compiled ,version 1.1 ,on local machine
When i build the client in rhp, i set port "7772" but when i receive the client i see a different port displayed, in my case "52524", why?

**Comment by quantumcore** [comment]
> When i build the client in rhp, i set port "7772" but when i receive the client i see a different port displayed, in my case "52524", why?

That IP and Port is the Client IP Address and port. The address from which the client is connecting from, Not the address where the client is connecting to. Your port ``7772`` is correct and the client did connect to it. But Port ``52524`` is the Clients port.

In networking, In order to receive connections you need to bind a Host and port together and listen on it. But to connect you need a server host and port. When connecting, The Client will get it's own port number automatically. 

In RHP Main table; **IP** and **Port** are the Client IP and Client Port.

**Comment by quantumcore** [comment]
Reopen if you want to add something.
