### ISSUE TITLE
UI problem

### ISSUE THREAD

**Issue by Pernat1y** [quantumcored/remote_hacker_probe#8]
After starting RHP.jar (java -jar RHP.jar) on both Windows 10 and Fedora 34, all I get is window without any elements.
Latest Java 16 JDK is installed on both OSes.
I know that this project is not updated, but it would be nice to have a fix...

![image](https://user-images.githubusercontent.com/29379145/126368009-a162e10d-c4b2-4e61-9d66-7fb97012de3b.png)

![image](https://user-images.githubusercontent.com/29379145/126368177-60023f2e-58bd-4b81-8830-0e3111648e16.png)

**Comment by Pernat1y** [comment]
PS. Just tested with JDK 15 on Windows and everything looks OK. So the problem is with latest JDK 16.

**Comment by quantumcore** [comment]
Sorry for the late reply.

But yes, The problem is with the java. It's working OK with java se 15 but doesn't show up anything on java se 16.
I have no idea what's the cause, but just use Java se 15.

**Comment by quantumcore** [comment]
Fixed here.
https://github.com/quantumcore/remote_hacker_probe/releases/tag/V.2.1
